### PR TITLE
 Gathered all important info

### PR DESCRIPTION
**Pull request by soarn**
Grabbed information from all over the site and compiled it into this nice little README file!

### CODE REVIEW

**Comment by Chew** [comment]
Why is everything in one readme? WE HAVE A WEBSITE! WE DON'T EVEN NEED A README

**Comment by soarn** [comment]
Check out the final change, It's just going with what you said.

**Comment by Chew** [comment]
You know, you're really over complicating things.

**Comment by soarn** [comment]
I'm sorry I over complicated everything.

**Pull request merged**
