### PR TITLE
Started Work On the README file

### PR DESCRIPTION
**Pull request by soarn**

### CODE REVIEW

**Comment by Chew** [comment]
But we don't NEED a readme.
We have index, and that's all we need.

**Comment by Chew** [comment]
Anything more than "This is the repository for the [ChewCraft IRC network server](http://irc.chew.pro)" is excessive and belongs in info/ or help/

**Comment by soarn** [comment]
I understand that, but it lets people know all that stuff from the main page instead of having to delve into other files for part of the information when it can just be centralized right on the front page.

**Comment by Chew** [comment]
Well, the website is for everything. If I wanted people to use github for all info I'd use the wikis, maybe not even have a repository at all.

**Pull request closed without merging**
