### PR TITLE
Added in-game role to Forastha

### PR DESCRIPTION
**Pull request by soarn**

### CODE REVIEW

**Comment by Chew** [comment]
I don't see a use in this. It's also technically factually incorrect.

**Comment by Chew** [comment]
Sell this to me and I may reconsider.

**Comment by notmega** [comment]
Please change your GitHub name! I keep forgetting who you are!

**Comment by soarn** [comment]
I think that it would look a lot more professional for the site to display your in-game role due to the fact that mine is on there as well.  Of if you don't want it to say "Owner" I'll delete this PR keep the branch and then change it so it says "Admin".

**Review by Chew — CHANGES_REQUESTED** [review]
Make it In-Game Admin and i'll take it

**Comment by soarn** [comment]
Changed, can you 
> m
> e
> r
> g
> e
> ?

**Review by Chew — APPROVED** [review]

**Pull request merged**
